name: Bump Version and Publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cÃ³digo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Configurar Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Instalar dependÃªncias
        run: |
          npm ci

      - name: Build do projeto
        run: npm run build

      - name: Bump de versÃ£o (minor)
        run: |
          npm version minor -m "ci: release %s [skip ci]"

      - name: Publicar no NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tag e versionamento para o GitHub
        run: |
          git push origin develop --follow-tags

      - name : Enviar email de notificaÃ§Ã£o
        uses:  dawidd6/action-send-mail@v3
        with: 
              server_address: smtp.gmail.com
              server_port: 465
              secure: true
              username: ${{ secrets.EMAIL_USER }}
              password: ${{ secrets.EMAIL_PASS }}
              subject: "ğŸ“¦ Novo pacote publicado: v${{ steps.package_version.outputs.version }}"
              body:  |
                  âœ… PublicaÃ§Ã£o concluÃ­da com sucesso!,
                  
                  ğŸ“ RepositÃ³rio: ${{ github.repository }}
                  ğŸ”– VersÃ£o: v${{ steps.package_version.outputs.version }}
                  ğŸ”— Commit: https://github.com/$%7B%7B github.repository }}/commit/${{ github.sha }}
                  ğŸ“¦ NPM: https://www.npmjs.com/package/spark-generators-lib
              to: caiochiabaioliveira@gmail.com
              from: GitHub Actions <${{ secrets.EMAIL_USER }}>
