name: Bump Version and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Configurar Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Instalar depend√™ncias
        run: |
          npm ci

      - name: Build do projeto
        run: npm run build

      - name: An√°lise com SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Bump de vers√£o (minor)
        run: |
          npm version minor -m "ci: release %s [skip ci]"

      - name: Publicar no NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tag e versionamento para o GitHub
        run: |
          git push origin develop --follow-tags

      - name : Enviar email de notifica√ß√£o
        uses:  dawidd6/action-send-mail@v3
        with: 
              server_address: smtp.gmail.com
              server_port: 465
              secure: true
              username: ${{ secrets.EMAIL_USER }}
              password: ${{ secrets.EMAIL_PASS }}
              subject: "üì¶ Novo pacote publicado: v${{ steps.package_version.outputs.version }}"
              body:  |
                  ‚úÖ Publica√ß√£o conclu√≠da com sucesso!
                  
                  üìÅ Reposit√≥rio: ${{ github.repository }}
                  üîñ Vers√£o: ${{ steps.package_version.outputs.version }}
                  üì¶ NPM: https://www.npmjs.com/package/spark-generators-lib
              to: caiochiabaioliveira@gmail.com, diegobrangel8@gmail.com, valentimcaldeira100@gmail.com, Lucas.codeco2@gmail.com, brunoowcx1@gmail.com
              from: GitHub Actions <${{ secrets.EMAIL_USER }}>
