name: Bump Version and Publish

on:
  push:
    branches:
      - devolop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cÃ³digo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Configurar Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Instalar dependÃªncias
        run: |
          npm ci

      - name: Build do projeto
        run: npm run build && npx tsc
          
      - name: Bump de versÃ£o (minor)
        id: package_version
        run: |
          VERSION=$(npm version minor -m "ci: release %s [skip ci]") # Removido o '|' extra e indentado corretamente
          echo "version=$VERSION" >> $GITHUB_OUTPUT    

      - name: Publicar no NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tag e versionamento para o GitHub
        run: |
          git push origin develop --follow-tags

      - name: Apagar tags antigas
        run: |
          # ObtÃ©m a tag mais recente (a Ãºltima criada)
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)

          echo "Mantendo a tag mais recente: $latest_tag"

          # Lista todas as tags, exclui a mais recente e deleta as demais
          for tag in $(git tag); do
            if [ "$tag" != "$latest_tag" ]; then
              git push --delete origin "$tag"
              git tag -d "$tag"
              echo "Tag apagada: $tag"
            fi
          done
      - name: Definir timestamp
        id: date
        run: echo "timestamp=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$GITHUB_OUTPUT"

        
      - name : Enviar email de notificaÃ§Ã£o
        uses:  dawidd6/action-send-mail@v3
        with: 
              server_address: smtp.gmail.com
              server_port: 465
              secure: true
              username: ${{ secrets.EMAIL_USER }}
              password: ${{ secrets.EMAIL_PASS }}
              subject: "ğŸ“¦ Novo pacote publicado: v${{ steps.package_version.outputs.version }}"
              html_body:  <p>O pacote foi publicado com sucesso no NPM.</p>

                <ul>
                  <li><strong>ğŸ“ RepositÃ³rio:</strong> ${{ github.repository }}</li>
                  <li><strong>ğŸ”– VersÃ£o:</strong> ${{ steps.package_version.outputs.version }}</li>
                  <li><strong>ğŸ•’ Data:</strong> ${{ github.event.head_commit.timestamp }}</li>
                  <li><strong>ğŸ‘¤ Autor:</strong> ${{ github.event.head_commit.author.name }}</li>
                  <li><strong>ğŸ”— Commit:</strong>
                    <a href="https://github.com/${{ github.repository }}/commit/${{ github.sha }}">
                      Ver commit
                    </a>
                  </li>
                </ul>

                <a class="button" href="https://www.npmjs.com/package/spark-generators-lib" target="_blank">
                  Acessar pacote no NPM
                </a>

                <div class="footer">
                  Enviado automaticamente por GitHub Actions â€¢ spark-generators-lib
                </div>
                </div>
              to: caiochiabaioliveira@gmail.com, diegobrangel8@gmail.com, valentimcaldeira100@gmail.com, Lucas.codeco2@gmail.com, brunoowcx1@gmail.com, lemelting53@gmail.com
              from: GitHub Actions <${{ secrets.EMAIL_USER }}>